name: CI/CD Pipeline
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          cd path/to/your/package.json/directory
          npm install

      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: pip install -r requirements.txt

      - name: Test with Pytest
        run: pytest --cov --junitxml=junit.xml

      - name: Upload Coverage to Codecov
        if: success()
        run: bash <(curl -s https://codecov.io/bash)